#!/usr/bin/python
import sys
import wizbit
from os.path import abspath, exists
from subprocess import CalledProcessError

try:
    if sys.argv[1] == "create":
        wizbit.create(abspath(sys.argv[2]))
    elif sys.argv[1] == "clone":
        newwizbit = abspath(sys.argv[3])
        if exists(newwizbit):
            print "clone: %s already exists!" % (sys.argv[3])
            sys.exit(1)
        wizbit.clone(sys.argv[2], newwizbit)
    elif sys.argv[1] == "add":
        wizbit.add(sys.argv[2], sys.argv[3])
    elif sys.argv[1] == "update":
        wizbit.update(sys.argv[2], sys.argv[3])
    elif sys.argv[1] == "log":
        if (len(sys.argv) > 3):
            wizbit.log (sys.argv[2], sys.argv[3]+".git")
        else:
            wizbit.log_all (sys.argv[2])
    elif sys.argv[1] == "checkout":
        wizbit.checkout (sys.argv[2], sys.argv[3], sys.argv[4])

except CalledProcessError, e:
    print e
    sys.exit(2)
