#!/usr/bin/python
import sys
from os.path import abspath, exists
from subprocess import CalledProcessError

import wizbit
from wizbit import Directory

try:
    if sys.argv[1] == "create":
	# create directory
	Directory.create(abspath(sys.argv[2]))
    elif sys.argv[1] == "clone":
	# clone directory remotedirid remotehost
        newwizbit = abspath(sys.argv[2])
        if exists(newwizbit):
            print "clone: %s already exists!" % (sys.argv[2])
            sys.exit(1)
	Directory.clone(newwizbit, sys.argv[3], sys.argv[4])	
    elif sys.argv[1] == "add":
	Directory.add(sys.argv[2], sys.argv[3])
    elif sys.argv[1] == "update":
	Directory.update(sys.argv[2], sys.argv[3], sys.argv[4])	

except CalledProcessError, e:
    print e
    sys.exit(2)
